### ISSUE TITLE
Release checklist for 0.4

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#132]
- [x] documentation #131 
- [x] bump version numbers
- [x] new pypi package
- [x] new docs on pythonhosted

**Comment by mperrin** [comment]
FYI to @josePhoenix - As of commit faf3e56 I think ``poppy`` is all ready to go. I am just going to hold off on pulling the trigger in case any last minute minor fixes are needed in the course of polishing the ``webbpsf`` release.

**Comment by josePhoenix** [comment]
Sounds good.

The only other thing I can think of is whether you want to fiddle with the way the `Instrument.display()` or `Instrument.calcPSF(display=True)` plots look. That might not be worth the trouble, because I think at least one of those is totally overridden in WebbPSF anyway.
